# Generated by Django 4.2.1 on 2023-08-05 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_rename_credit_course_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
    ]
